name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: automation_results
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      # --- CORREÇÃO APLICADA AQUI ---
      # Adicionando SITE_URL e BROWSER às variáveis de ambiente
      env:
        SITE_URL: https://advantageonlineshopping.com/#/
        BROWSER: headlesschrome
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_NAME: automation_results
        DB_USER: root
        DB_PASS: root
      run: robot --outputdir results/ testes/

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-framework-results
        path: results/